#!/usr/bin/env bash

set -e
set -u
set -o pipefail

script_path=$(readlink -e "${BASH_SOURCE[0]}")
script_dir="${script_path%/*}"

#source ../../util/util.sh
source "${script_dir}/../../util/util.sh"

declare app_name="${1:-talend_sample_container_app}"
declare project_name="${2:-SE_DEMO}"
declare sample_home="${3:-${TALEND_DOCKER_SAMPLE_HOME:-${HOME}/talend/docker/sample}}"

if [ "${1:-}" == "-h" ]; then
    declare usage
    define usage <<EOF
Usage

    ./init-app [ <app_name> [ <project_name> [ <sample_home> ] ] ]

Defaults:

    app_name: "talend_sample_container_app"
    project_name: "SE_DEMO"
    sample_home: TALEND_DOCKER_SAMPLE_HOME or "${HOME}/talend/docker/sample"
EOF
    printf "\n%s\n\n" "${usage}" >&2
    exit
fi

declare global_dir="${sample_home}"
global_dir=$(readlink -m "${global_dir}")
declare project_dir="${global_dir}/${project_name}"
declare app_dir="${project_dir}/${app_name}"

printf "\n"
printf "Setting up Talend docker sample environment\n"
printf "global_dir=%s\n" "${global_dir}"
printf "project_dir=%s\n" "${project_dir}"
printf "app_dir=%s\n" "${app_dir}"
printf "\n"

# create shared input directory
mkdir -p "${app_dir}"
cp -r "${script_dir}/data/in" "${app_dir}"
printf "Application input copied to: %s\n" "${app_dir}/in"
printf "\n"
