#!/usr/bin/env bash

set -e
set -u
set -o pipefail

declare -r job_id="${1:-}"
declare -r job_name="${2:-t0_docker_create_customer}"
declare -r app_name="${3:-talend_sample_container_app}"
declare -r project_name="${4:-SE_DEMO}"
declare -r sample_home="${5:-${TALEND_DOCKER_SAMPLE_HOME:-${HOME}/talend/docker/sample}}"



declare -r usage="./clean [ <job_id> [ <job_name> [ <app_name> [ <project_name> [ <sample_home> ] ] ] ] ]"

[ "${1:-}" == "-h" ] && echo "${usage}" 1>&2 && exit 1

declare sample_dir
sample_dir=$(readlink -m "${sample_home}")
declare -r global_dir="${sample_dir}"
declare -r project_dir="${global_dir}/${project_name}"
declare -r app_dir="${project_dir}/${app_name}"
declare -r job_dir="${app_dir}/${job_name}"
declare -r job_instance_dir="${job_dir}/${job_id}"

if [ -n "${job_id}" ]; then
    sudo rm -rf "${job_instance_dir}"
else
    sudo rm -rf "${job_dir}"
fi
